### ISSUE TITLE
[Frontend/Backend] Discussion: user logout

### ISSUE THREAD

**Issue by MasterSparkInYourFace** [digitalents-academy/interactive-comment-section#4]
Once a user has logged out, what should happen to the user object?

The current logic is to remove it from the message root entirely so that when the message root is serialized into JSON for the client, all messages from those users are serialized as "deleted user" with a default profile picture.
This causes clutter from deleted users in the comment tree since our system is based around short-lived users.

### Proposed solutions (you can also suggest more instead of discussing these ones):

- [ ] Instead of deleting the user object, mark it as "deleted" or "inactive" instead
  - Will result in a growing amount of non-reusable user objects with associated profile pictures taking up space.
    - There are solutions to allow object re-use, but they add complexity to the current system (message tagging with session tokens etc.)
- [ ] Delete messages from deleted users
  - Results in confusion as comment trees become broken by replies to non-existent messages
- [ ] Hide messages from deleted users
  - Simplest solution to implement. Can be done entirely on the frontend by checking if a message's sender is "deleted user"

**Comment by durzinger** [comment]
I'll suggest that the user identifies with a password and can edit and delete own messages

...or

everyone can edit and delete everyone's messages in the MVP version

**Comment by durzinger** [comment]
----------------------------------------
|___Register______|______Login_______|
|                                                        
| [_username_______]                         
| [_password_______]                          
|                                                         
|________________________[_button_]__ 


The login modal could have two different tabs for registration and login

**Comment by MasterSparkInYourFace** [comment]
solution: implemented a password system that uses sha256 to hash passwords that are then sent to the server and stored there. these are used to authenticate users during login. when logging in, each client is sent a session token for that user. in addition to being regenerated after logout, these tokens are not saved to disk and generated randomly on each server boot.
